name: ✨ Feature Request
description: Propose a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your proposal! It helps if you describe "what problem you want to solve → what you want to achieve".

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: The problem you want to solve or the background (why is this needed?)
      placeholder: "Currently, it's difficult to... / I can't... / etc."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What behavior/API would you like? (Code examples are welcome)
      placeholder: |
        Example:
        - Add xxx option to createSerialClient
        - Change return value of getReadStream to xxx
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other alternatives (workarounds) or comparison with existing libraries, if any
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Reference links, use cases, implementation ideas, etc.
    validations:
      required: false
